name: CI

on:
  push:
    branches:
      - master
jobs:
  build:
    strategy:
      matrix:
        python-version: [3.12, 3.11, 3.10, 3.9, 3.8]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: run wherepy
        run: |
          python wherepy.py --search-dir ${{ runner.tool_cache }}/Python --error-if-not-found
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: setup dependencies
        run: |
          pip install poetry twine
          poetry install
      # - name: run tests
      #   run: poetry run pytest -x tests/
      - name: publish
        if: ${{ startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/dev-ci')  }}
        run: |
          poetry build
          twine upload --skip-existing dist/* -u $PYPI_USER -p $PYPI_PWD
        env:
          PYPI_USER: __token__
          PYPI_PWD: ${{ secrets.PYPI_TOKEN }}
