name: CI

on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.12
      - name: discover python
        run: |
          which python
          echo ${{ runner.tool_cache }}/Python
          pip install typer
      - name: run wherepy
        run: |
          cat wherepy.py
          python wherepy.py --help
          python wherepy.py --search-dir ${{ runner.tool_cache }}/Python --error-if-not-found
